### ISSUE TITLE
Can I send some pull requests?

### ISSUE THREAD

**Issue by correa** [webcamoid/akvirtualcamera#1]
Is the Manager folder the sample application? What do you have in mind for it? Would you mind if I try to implement something?

Also, it would be good to have CMake support too, Qt itself is switching to cmake and it will be used to build Qt6.

**Comment by correa** [comment]
I was just going to use QCommandLineParser then I realised, do you want manager to be free of Qt as a dependency?

**Comment by hipersayanX** [comment]
Yes, it will be Qt and other third party libraries free, it must not have dependencies with anything else beside system provided native libraries.
