### ISSUE TITLE
No service + debug log question

### ISSUE THREAD

**Issue by markednmbr1** [webcamoid/akvirtualcamera#10]
It looks like there is no "Webcamoid virtual camera service" when you just install the akvirtualcamera only. Is that correct?

Also can you please advise what the debug logs should be named in C:\Windows\Temp and C:\Users\%USERNAME%\AppData\Local\Temp ?

**Comment by hipersayanX** [comment]
>It looks like there is no "Webcamoid virtual camera service" when you just install the akvirtualcamera only. Is that correct?

This is a bug. I'll fix it before release.

>Also can you please advise what the debug logs should be named in C:\Windows\Temp and C:\Users%USERNAME%\AppData\Local\Temp ?

There are two logs, one located at _C:\Users\%USERNAME%\AppData\Local\Temp_ wihich is named AkVirtualCamera-DATETIME.log, which debugs the plugin, and the other located at _C:\Windows\Temp_ wihich is named AkVCamAssistant-DATETIME.log, which debugs the service.

**Comment by hipersayanX** [comment]
I've added detailed [documentation](https://github.com/webcamoid/akvirtualcamera/wiki) on how to use the vcam. Closing.
