### ISSUE TITLE
System.OutOfMemory

### ISSUE THREAD

**Issue by markednmbr1** [webcamoid/akvirtualcamera#11]
Hi, I am piping in a stream from ffmpeg to AkVCamManager as follows:

.\ffmpeg.exe -rtsp_transport tcp -i rtsp://10.101.0.100:8554/live -f rawvideo - | .\AkVCamManager.exe stream AkVCamVideoDevice0 RGB24 640 480 30

This constantly uses memory until it runs out and throws the following error:

Program 'AkVCamManager.exe' failed to run: Exception of type 'System.OutOfMemoryException' was thrown.At line:1 char:83
+ ... awvideo - | & 'C:\Program Files\AkVirtualCamera.plugin\x64\AkVCamMana ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\ffmpeg.exe -rtsp_transport tcp -i rtsp://10.101.0.100:8554/live -f  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by hipersayanX** [comment]
This should be already fixed with the latest commits.
