### ISSUE TITLE
where is the device

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/akvirtualcamera#14]
Hello,

I created a device as shown below. 

1.  What is the path to this device?
2. I do not see this device under avfoundation list. WebCamoid generated device is visible in the list.
3. How can I use VLC to open this device and play the contents.

Thanks

$ AkVCamManager add-device "AvailCamera0"
Device created as "AkVCamVideoDevice"0
$ AkVCamManager devices
+----------------------+--------------+
| Device               | Description  |
+----------------------+--------------+
| "AkVCamVideoDevice"0 | AvailCamera0 |
+----------------------+--------------+

**Comment by hipersayanX** [comment]
Once you created a device you must add a format and update.

```
AkVCamManager add-format AkVCamVideoDevice0 RGB24 640 480 30
AkVCamManager update
```

If everything was ok, then you should be able to list it with for example ffmpeg:

```
ffmpeg -f avfoundation -list_devices true -i ""
```

**Comment by shersoni610** [comment]
Hello,

I followed the steps, but still I can  not see the device in avfoundation list. What could
be the problem?

$ ./AkVCamManager devices
+----------------------+--------------+
| Device               | Description  |
+----------------------+--------------+
| "AkVCamVideoDevice"0 | AvailCamera0 |
+----------------------+--------------+
$ AkVCamManager add-format \"AkVCamVideoDevice\"0 RGB24 1920 1080 30
$ ./AkVCamManager update

**Comment by hipersayanX** [comment]
I've fixed the bug already, remove the devices, install the latest daily build:

https://bintray.com/webcamoid/webcamoid/download_file?file_path=mac%2FAkVirtualCamera-daily-master-51.dmg
https://bintray.com/webcamoid/webcamoid/download_file?file_path=windows%2FAkVirtualCamera-daily-master-51-win64.exe

and  try again.

**Comment by shersoni610** [comment]
Hello,

Is the fix available in source code? I see the last update weeks ago.

Thanks

**Comment by hipersayanX** [comment]
Yes, if you compile from sources and you have the plugin already installed, just replace the files, otherwise you will need to install the service manually.

**Comment by shersoni610** [comment]
Thank you very much. If you could point me what changes are required then I will try to fix them.

Right now I called only two functions (1) addDevice (2) addFormat. Somehow, I do not see the device
in the list of avfoundation , therefore. I can render the images with OpenCV VideoCapture. I do not
know what additional functions should I call to start using the Webcam. I will greatly appreciate
if you could help out taking your little time.

Regards

**Comment by shersoni610** [comment]
There seems to identical functions in the API (a) addDevice (2) createDevice. Which 
one should be used when creating new devices?

**Comment by hipersayanX** [comment]
>Thank you very much. If you could point me what changes are required then I will try to fix them.

The code is fine, the quotes bug was introduced when changing the build system to cmake, [here](https://github.com/webcamoid/akvirtualcamera/blob/8eaf3fb31b76f55c1538411960e9bc96704e7afe/dshow/dshow.cmake#L34), and it was already fixed [here](https://github.com/webcamoid/akvirtualcamera/blob/e408aad47c081bd05330e50385766f14245439ae/dshow/dshow.cmake#L34), just make a ```git pull``` to get the changes.

>There seems to identical functions in the API (a) addDevice (2) createDevice.

Do you mean [this "API"](https://github.com/webcamoid/akvirtualcamera/blob/master/VCamUtils/src/ipcbridge.h)?

>Which one should be used when creating new devices?

None, the internal API is not guaranteed to be stable, for every single operation you want to do with the vcam, just call the manager.

**Comment by hipersayanX** [comment]
I've added the [documentation](https://github.com/webcamoid/akvirtualcamera/wiki) of the vcam. Closing.
