### ISSUE TITLE
add format

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/akvirtualcamera#15]
Hello,

I am trying to use add-format.  There seems to be some issue in the way I am
passing artguments. Can someone help?

$ ./AkVCamManager devices
+----------------------+--------------+
| Device               | Description  |
+----------------------+--------------+
| "AkVCamVideoDevice"0 | AvailCamera0 |
+----------------------+--------------+
$ AkVCamManager add-format AkVCamVideoDevice0 RGB24 640 480 30
'AkVCamVideoDevice0' doesn't exists.
$ AkVCamManager add-format "AkVCamVideoDevice"0 RGB24 640 480 30
'AkVCamVideoDevice0' doesn't exists.
$ AkVCamManager add-format AvailCamera0  RGB24 640 480 30
'AvailCamera0' doesn't exists.
$

**Comment by hipersayanX** [comment]
It seems to be a bug, Cmake included the quotes in the DEVICE_PREFIX macro. I will fix it later.
For now try with:

```
AkVCamManager add-format '"AkVCamVideoDevice"0' RGB24 640 480 30
```

**Comment by hipersayanX** [comment]
This was fixed in latest commits, closing.
