### ISSUE TITLE
Unrecognized target specifier. <service-target>....

### ISSUE THREAD

**Issue by phanmn** [webcamoid/akvirtualcamera#16]
Hi, I'm using mac (version 11.4) and trying to follow steps at `https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install` 

1. When I run command
```bash
launchctl enable system/ org.webcamoid.cmio.AkVCam.Assistant
```
the output is 
```
Unrecognized target specifier. <service-target> takes a form of <domain-target>/<service-id>.
Please refer to `man launchctl` for explanation of the <domain-target> specifiers.
```
Please give me some hints to solve this issue. Thank you!

**Comment by hipersayanX** [comment]
Typo error, it goes all together:

```
launchctl enable system/org.webcamoid.cmio.AkVCam.Assistant
```
I've fixed the wiki, thanks.
