### ISSUE TITLE
Question for collaboration 

### ISSUE THREAD

**Issue by JosipNizetic** [webcamoid/akvirtualcamera#21]
Hello,

I would like to apologize to contacting you like this but could not find any mail anywhere. 
We are small team who is developing software for Controlling Online Exams. Program consist of two main parts - Capture and Analyze. Capture program is installed on client pc and it is in focus her.
We did all coding in c++ on Windows platform with QT UI. Our problem is MAC support, as we don’t have much experience with it. So my question  would you be interested to make this transition for us. Of course we would be with you whole way just need some expert guidance.

If you are interested please tell me mail on which I can send you more details. So you can examine and tell your price, and we can agree on everything before continuing. 
If not I am very sorry for bothering you in this way..

Best regards,
Josip

**Comment by hipersayanX** [comment]
My mail appears in the commit log.
