### ISSUE TITLE
Unable to find virtual cam device in browser

### ISSUE THREAD

**Issue by Ajju2211** [webcamoid/akvirtualcamera#23]
### Unable to find virtual cam device in browser
I followed these steps but could not find that device created.
https://github.com/webcamoid/akvirtualcamera/wiki/Configure-the-cameras

**Comment by hipersayanX** [comment]
Which browser (Firefox or Chrome based)? which operating system? what is the output of this command: ```AkVCamManager --dump```?

**Comment by Ajju2211** [comment]
The output of the 
`AkVCamManager dump`
<?xml version="1.0" encoding="UTF-8" ?>
<info>
    <devices>
        <device>
            <id>AkVCamVideoDevice0</id>
            <description>Virtual Camera</description>
            <formats>
            </formats>
            <controls>
                <control>
                    <id>hflip</id>
                    <description>Horizontal Mirror</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
                <control>
                    <id>vflip</id>
                    <description>Vertical Mirror</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
                <control>
                    <id>scaling</id>
                    <description>Scaling</description>
                    <type>Menu</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                    <menu>
                        <item>Fast</item>
                        <item>Linear</item>
                    </menu>
                </control>
                <control>
                    <id>aspect_ratio</id>
                    <description>Aspect Ratio</description>
                    <type>Menu</type>
                    <minimum>0</minimum>
                    <maximum>2</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                    <menu>
                        <item>Ignore</item>
                        <item>Keep</item>
                        <item>Expanding</item>
                    </menu>
                </control>
                <control>
                    <id>swap_rgb</id>
                    <description>Swap RGB</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
            </controls>
        </device>
    </devices>
    <input-formats>
        <pixel-format>RGB24</pixel-format>
    </input-formats>
    <default-input-format>RGB24</default-input-format>
    <output-formats>
        <pixel-format>RGB32</pixel-format>
        <pixel-format>RGB24</pixel-format>
        <pixel-format>RGB16</pixel-format>
        <pixel-format>RGB15</pixel-format>
        <pixel-format>UYVY</pixel-format>
        <pixel-format>YUY2</pixel-format>
        <pixel-format>NV12</pixel-format>
    </output-formats>
    <default-output-format>YUY2</default-output-format>
    <clients>
    </clients>
    <picture></picture>
    <loglevel>-1</loglevel>
</info>`

**Comment by hipersayanX** [comment]
You haven't defined any format, [define some formats](https://github.com/webcamoid/akvirtualcamera/wiki/Configure-the-cameras#managing-the-formats) and then [update](https://github.com/webcamoid/akvirtualcamera/wiki/Configure-the-cameras#quick-rundown).
