### ISSUE TITLE
Example for AkVirtualCamera doesn't work

### ISSUE THREAD

**Issue by CodeMonkeee** [webcamoid/akvirtualcamera#25]
This project looks amazing and I would love to use it but there is one big issue. I seem to get loads of errors when using the example of streaming. I decided it may be my code so I made a new project and gave it a go, it still caused the same issue, is the example up to date? Am I missing something?

[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(51,25): error C2734: 'cmd': 'const' object must be initialized if not 'extern' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(55,5): error C2664: 'int snprintf(char *const ,const size_t,const char *const ,...)': cannot convert argument 1 from 'const char [1024]' to 'char *const ' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(55,14): message : Conversion loses qualifiers [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Windows Kits\10\Include\10.0.19041.0\ucrt\stdio.h(1919,37): message : see declaration of 'snprintf' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(68,76): error C2027: use of undefined type 'main::SECURITY_ATTRIBUTES' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(68): message : see declaration of 'main::SECURITY_ATTRIBUTES' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(69,74): error C2027: use of undefined type 'main::SECURITY_ATTRIBUTES' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(68): message : see declaration of 'main::SECURITY_ATTRIBUTES' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(80,25): error C2079: 'startupInfo' uses undefined struct 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(81,55): error C2027: use of undefined type 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(80): message : see declaration of 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(82,48): error C2027: use of undefined type 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(80): message : see declaration of 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(87,32): error C2079: 'procInfo' uses undefined struct 'main::PROCESS_INFORMATION' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(88,59): error C2027: use of undefined type 'main::PROCESS_INFORMATION' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(87): message : see declaration of 'main::PROCESS_INFORMATION' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(91,5): error C2664: 'BOOL CreateProcessA(LPCSTR,LPSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION)': cannot convert argument 2 from 'const char [1024]' to 'LPSTR' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(92,20): message : Conversion loses qualifiers [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Windows Kits\10\Include\10.0.19041.0\um\processthreadsapi.h(361,1): message : see declaration of 'CreateProcessA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(104,39): error C2440: 'initializing': cannot convert from 'void *' to 'char *' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(104,18): message : Conversion from 'void*' to pointer to non-'void' requires an explicit cast [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\main.cpp(107,11): error C3861: 'time': identifier not found [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
[build] Build finished with exit code 1

This is what each one said in the problems tab:
'cmd': 'const' object must be initialized if not 'extern' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'int snprintf(char *const ,const size_t,const char *const ,...)': cannot convert argument 1 from 'const char [1024]' to 'char *const ' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
use of undefined type 'main::SECURITY_ATTRIBUTES' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'startupInfo' uses undefined struct 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
use of undefined type 'main::STARTUPINFOA' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'procInfo' uses undefined struct 'main::PROCESS_INFORMATION' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
use of undefined type 'main::PROCESS_INFORMATION' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'BOOL CreateProcessA(LPCSTR,LPSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION)': cannot convert argument 2 from 'const char [1024]' to 'LPSTR' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'initializing': cannot convert from 'void *' to 'char *' [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]
'time': identifier not found [E:\Users\kaiha\OneDrive\Desktop\New folder - Copy\build\opencv.vcxproj]

**Comment by hipersayanX** [comment]
Did you opened a new account? continue in the previous issue #24

**Comment by CodeMonkeee** [comment]
Im confused. Do you mean you think I'm KaiH?

**Comment by hipersayanX** [comment]
@CodeMonkeee because you are using the same user name in the folder ```E:\Users\kaiha```, anyway is the same bug.
