### ISSUE TITLE
[question] Virtual devices not found in /dev/videoX

### ISSUE THREAD

**Issue by kirk86** [webcamoid/akvirtualcamera#32]
## Summary

I can't find any devices under `/dev/video` after successfully creating devices with `AkVCamManager`

## Current Behavior

Devices are created successfully, also they show in zoom but can't see them in vlc.

## Expected Behavior

After creating the devices I was expecting to see `/dev/video0`, `/dev/video1` etc.

How it should have work?
After creating devices expecting to see them under `/dev/video` or something like `/dev/media`

## Steps to Reproduce

1. OSX 11.5.1
2. install `AkVCamManager` from the binary `.pkg` file on the latest stable release
3. create a `config.ini` that creates 2 devices (output, capture)
4. check on `/dev/video*` for devices but nothing
5. `AkVCamManager devices`
```
+--------------------+--------------------------------+
| Device             | Description                    |
+--------------------+--------------------------------+
| AkVCamVideoDevice0 | Virtual Camera (output device) |
| AkVCamVideoDevice1 | Virtual Camera                 |
+--------------------+--------------------------------+
```

## Your Environment

* akvirtualcamera inormation: (9.1.0) (binary)
* Operating System information: (OSX) (11.5.1 Big Sur) (intel)

Am I missing something?

pinging @hipersayanX for visibility, thanks!

**Comment by hipersayanX** [comment]
>After creating the devices I was expecting to see /dev/video0, /dev/video1 etc.
>
>How it should have work?
>After creating devices expecting to see them under /dev/video or something like /dev/media

You are confusing GNU/Linux with Mac, /dev/video devices are exclusive of V4L2 which is not implemented in Mac, Mac uses AVFoundation for camera capture which is a completely different API, you will never see any /dev/video or anything like that there.

**Comment by kirk86** [comment]
Thanks for the clarification!

I'm trying to use a program which reads form the virtual camera and does some processing and then pushes that onto the real device.

The issue is that the program was written with V4L2 in mind and in its config file I have the following lines:
```
virtual_video_device: "/dev/video0"
real_video_device: "/dev/video1"
```

Is there any possibility to replace `/dev/video0` with `AkVCamManager` after creating devices? If so how can I achieve that? 

Thanks!

**Comment by hipersayanX** [comment]
>I'm trying to use a program which reads form the **virtual camera** and does some processing and then pushes that onto the **real device**.

Hmmm.... maybe you mean in the opposite way?

>I'm trying to use a program which reads form the **real device** and does some processing and then pushes that onto the **virtual camera**.

Because the first sentence makes no technical sense.

>Is there any possibility to replace /dev/video0 with AkVCamManager after creating devices? If so how can I achieve that?

I don't know what program are you talking about, but if you want to push frames from your program to the virtual camera you can check [here](https://github.com/webcamoid/akvirtualcamera/tree/master/share/examples) the code examples.

**Comment by kirk86** [comment]
> Hmmm.... maybe you mean in the opposite way?

Yes, you are correct, sorry about the wrong statement.

> if you want to push frames from your program to the virtual camera you can check [here](https://github.com/webcamoid/akvirtualcamera/tree/master/share/examples) the code examples

Thanks for this I wasn't aware of it.
If you don't mind me asking a couple of questions about the code examples.

1. It seem that the code example should be running for 30 secs, right?
2. What type of data does `AkVCamManager stream` expects when writing to it? It seems that you're sending string `char* buffer[]`, right?
3. Can we send directly float type of array data of size array[3, width, height]?

I tried to recreate the c code example into python but it seems that my translation of it runs for ever.

I first created two virtual cameras, one output and one capture, then used the following code to write frames to the output virtual camera, but it seems to be running for ever, do you have any clues what might be going wrong?

Finally, is there a way to see what is being written to the virtual camera while the script is running, for debugging purposes and verification?


```
import os
import time
import numpy as np


fps = 30
duration_seconds = 30
n_frames = fps * duration_seconds
camera = "AkVCamVideoDevice0"
camera_format = "RGB24"
width = 640
height = 480

cmd = "/Applications/AkVirtualCamera/AkVirtualCamera.plugin/Contents/Resources/AkVCamManager stream {} {} {} {}".format(
      camera, camera_format, width, height)

proc = os.popen(cmd, mode='w')

#Allocate the frame buffer.
buffer_size = 3 * width * height;
buffer = np.zeros((buffer_size, 1))

# Generate some random noise frames.
np.random.seed(2021)

for i in range(n_frames):
    # Write the frame data to the buffer.
    for j in range(buffer_size):
        buffer[j] = np.random.rand(1)[0] + np.random.rand(1)[0]

    proc.write(np.array2string(buffer))

    time.sleep(1)

print(buffer)
# Stop the stream.
proc.close()
```

**Comment by kirk86** [comment]
@hipersayanX 
I have a question if you don't mind.?
After the example code I'm able to write to the virtual camera using akvcammanager but for some reason the content is not displayed properly.

For instance, I have the following image which I'm reading from disk, the image is an array[width=700, height=561, channels=3]
I'm resizing it to 1024x720 to match the setting of the virtual camera

![image](https://user-images.githubusercontent.com/2902390/144722052-7cff6af7-9cf7-4555-9ef4-54b872d4a0c6.png)

But when I write this image frame to the virtual camera I get the following output
Any ideas what I'm doing wrong here?

![image](https://user-images.githubusercontent.com/2902390/144722007-62746d80-d943-429e-8ea7-f82c6f538d00.png)

**Comment by hipersayanX** [comment]
If the scaling is correct, it cold be maybe that you are sending the frames y the wrong format.
Each color component is a 24 bits long: 8 bits Red, 8 bits Green, 8 bits Blue, in that order, no padding bits.
Each frame is read from top-left corner to bottom right corner, lines must not be padded, and the width must be multiple of 32.
For example, if you want to send a RGB24 1024x720 frame, the line size should be ```1024 * 24 / 8 == 3072```, the frame size should be ```3072 * 720 == 2211840```.
If everything is correct you should be able to see the frame in the other side, else the code you are using for scaling is wrong.

**Comment by kirk86** [comment]
Thanks, I tried all possible formats and only RGB24 seems stable, but the colours are distorted.

> For example, if you want to send a RGB24 1024x720 frame, the line size should be `1024 * 24 / 8 == 3072`, the frame size should be `3072 * 720 == 2211840`.

I have no idea what that means. I'm reading an image using opencv which returns back a numpy arrray of size 1024x720x3 and type float32, then I transform that into a type of uint8, and send it as bytes to the virtual camera. Am I doing sth wrong?


Real image:
![image](https://user-images.githubusercontent.com/2902390/144748527-5dc369b3-e8fe-40f8-87a0-8a8ba9afc45f.png)


This is what I get written on the virtual camera
![image](https://user-images.githubusercontent.com/2902390/144748444-92930bf4-44d5-44a4-b81f-cfcb32788053.png)

**Comment by hipersayanX** [comment]
That's because OpenCV is ordering the components as BGR instead of RGB, just swap red and blue components.

**Comment by kirk86** [comment]
Thanks for pointing that out, any ideas as to why the other formats produce artifacts?

**Comment by hipersayanX** [comment]
>any ideas as to why the other formats produce artifacts?

Because you are sending the frames in the wrong format, only RGB24 is supported for now.

**Comment by kirk86** [comment]
> only RGB24 is supported for now

Most probably this is the case since I've corrected the format after your suggestion.
