### ISSUE TITLE
How to acces the actual camera

### ISSUE THREAD

**Issue by Vladimir-Moskalenko** [webcamoid/akvirtualcamera#34]
Is there any way I can uninstall it, or access the original camera?
I have macOS Catalina, macBook Pro mid-2012

**Comment by hipersayanX** [comment]
>Is there any way I can uninstall it

Run the uninstall script in the install folder.

>or access the original camera?

The hardware camera is always accessible.

**Comment by Vladimir-Moskalenko** [comment]
In the app, select Cameras > FaceTime Camera
