### ISSUE TITLE
Android and IOS

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [webcamoid/akvirtualcamera#35]
Is it technically feasible to expand akvirtualcamera to IOS and Android?

**Comment by ROBERT-MCDOWELL** [comment]
what about create a stream encoded locally and grab it from local ip?

**Comment by hipersayanX** [comment]
Yes, someone else also asked for a [similar thing](https://github.com/webcamoid/webcamoid/issues/399), my idea is to connect Webcamoid in PC and phone and send the video stream in both directions, but anyway that is not related to the virtual camera.

**Comment by ROBERT-MCDOWELL** [comment]
ha yes I recall now, anyhow I will give you back some new info if any!
