### ISSUE TITLE
zoom.us can't find virtual camera in Mac

### ISSUE THREAD

**Issue by dx12346789** [webcamoid/akvirtualcamera#36]
I use the viki's [Build and install](https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install) to install virtual camera.But I can't find the camera in zoom.us. 
Following my terminal code:
```
soda@sodadeiMac Resources % ./AkVCamManager devices
soda@sodadeiMac Resources % ./AkVCamManager load setting.ini 
soda@sodadeiMac Resources % ./AkVCamManager devices
+--------------------+-------------------------+
| Device             | Description             |
+--------------------+-------------------------+
| AkVCamVideoDevice0 | My Other Virtual Camera |
| MyFakeCamera0      | My Virtual Camera       |
+--------------------+-------------------------+
soda@sodadeiMac Resources % ./AkVCamManager update
soda@sodadeiMac Resources % ./AkVCamManager formats MyFakeCamera0
0: YUY2 1280x720 30/1 FPS
```
and the setting.ini:
```
[Cameras]
cameras/size = 2

cameras/1/description = My Virtual Camera
cameras/1/formats = 1
cameras/1/id = MyFakeCamera0

cameras/2/description = My Other Virtual Camera
cameras/2/formats = 1, 2

[Formats]
formats/size = 2

formats/1/format = YUY2
formats/1/width = 1280
formats/1/height = 720
formats/1/fps = 30

formats/2/format = RGB24
formats/2/width = 1280
formats/2/height = 720
formats/2/fps = 30

[General]
default_frame = /Users/soda/xcodepoject/akvirtualcamera-master/cmake_build/build/AkVirtualCamera.plugin/Contents/Resources/default.jpg 

```
Is there anything I missed?

**Comment by hipersayanX** [comment]
Dit you [installed the service](https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install#install)?

**Comment by dx12346789** [comment]
Thank you for your reply.
Here are my services:
```
soda@sodadeiMac Resources % launchctl list | grep -E "Assistant"
-	0	com.apple.AddressBook.AssistantService
soda@sodadeiMac Resources % sudo launchctl list | grep -E "Assistant"
20686	0	org.webcamoid.cmio.AkVCam.Assistant
-	0	com.apple.cmio.iOSScreenCaptureAssistant
-	0	com.apple.systempreferences.cacheAssistant
-	0	com.apple.cmio.AppleCameraAssistant
-	0	com.apple.cmio.IIDCVideoAssistant
276	0	com.apple.cmio.VDCAssistant
-	0	com.apple.cmio.AVCAssistant
```
The first service returned by sudo.

I add service by this code:
```
sudo launchctl enable system/org.webcamoid.cmio.AkVCam.Assistant

sudo launchctl bootstrap system /Library/LaunchDaemons/org.webcamoid.cmio.AkVCam.Assistant.plist
```
I copy and paste it to the terminal.

**Comment by dx12346789** [comment]
My proccess is as follows:
1. Make alias for AkVirtualCamera.plugin to /Library/CoreMediaIO/Plug-Ins/DAL/
2. Copy the code to create plist file to /Library/LaunchDaemons/
3. Create the service with the above code
4. Then use `sudo launchctl start /Library/LaunchDaemons/org.webcamoid.cmio.AkVCam.Assistant.plist` to start the service

**Comment by hipersayanX** [comment]
Everything seems to be correct. Are you using an x86_64 or a M1 processor? Does installing the virtual camera using the [pkg](https://github.com/webcamoid/akvirtualcamera/releases/tag/9.1.0) works?

**Comment by dx12346789** [comment]
oh. My zoom can find the virtual camera. I can't understand it.
I changed the camera format from YUY2 to RGB24, then zoom can find it.
After that I changed to YUY2, zoom can also found it.

**Comment by dx12346789** [comment]
When I use:
`ffmpeg -i ./1.mp4 -pix_fmt rgb24 -f rawvideo - | ./AkVCamManager stream MyFakeCamera0 RGB24 1280 720`
Then I changed size from 1280x720 to 640x480,It's also slow.  
It look like slower that the original.
What can i do?

**Comment by hipersayanX** [comment]
>oh. My zoom can find the virtual camera. I can't understand it.

Could it be that you closed and then reopened Zoom? that could be the reason because it can find the camera now.

>It look like slower that the original.

The vcam still needs a lot of optimizations.

>What can i do?

If you know, C++ then start optimizing the code.
