### ISSUE TITLE
[Question] using both real camera and virtual camera simultaneously (split cam)

### ISSUE THREAD

**Issue by zaher83** [webcamoid/akvirtualcamera#38]
# Does akvirtualcamera support split webcams?

Hi,
After streaming real camera to virtual one created using akvirtualcamera, on Windows 10 (64), the Real Camera(integrated webcam)  was not accessible by other programs like zoom, google meet and others.

So I just want to know if is it possible to do that if yes please guide.

Thanks

**Comment by zaher83** [comment]
@hipersayanX yes I know I can stream video to multiple virtual cameras, but my case is streaming ***webacam*** to multiple virtual cameras.
When I tried doing that, the ***webcam*** wasn't accessible by other apps (like zoom, skype..) 

My objective is to create two ***webcams*** that could be accessible at the same time.

**Comment by hipersayanX** [comment]
As I said before, you capture from the real camera, send the output to the virtual cameras, and make the programs capture from those virtual cameras.

>When I tried doing that, the webcam wasn't accessible by other apps (like zoom, skype..)

You can check the support status [here](https://github.com/webcamoid/akvirtualcamera/wiki/Support-status), and you can read the [wiki](https://github.com/webcamoid/akvirtualcamera/wiki) if you have any question on how to configure the camera.
