### ISSUE TITLE
Webcamoid 9.0.0 hangs after downloading and installing akvirtualcamera

### ISSUE THREAD

**Issue by KWB** [webcamoid/akvirtualcamera#43]
I install _akvirtualcamera_ via the Webcamoid 9.0.0 settings ("The virtual camera is not installed, do you want to install it?"). This installs _akvirtualcamera_windows 9.1.0_. After completing and restarting _Webcamoid 9.0.0_ hangs forever.

Uninstalling _akvirtualcamera_windows_ solves the issue. I have also manually tried _akvirtualcamera_windows 9.0.0_ with the same result (Webcamoid hanging).

Anything I can do to resolve the issue?

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
System Name	DELL-INSPIRON
System Model	Inspiron 7548
System Type	x64-based PC
```

Edit: Also have tested the daily build of Webcamoid, same issue. I use a non standard path **without** space for installation, `P:\Tools\AkVirtualCamera`

**Comment by cjbarth** [comment]
Does this issue behave like https://github.com/webcamoid/webcamoid/issues/497 or https://github.com/webcamoid/webcamoid/issues/527? If so, this might be a duplicate and/or posted in the wrong repo.
