### ISSUE TITLE
Sending frames from python

### ISSUE THREAD

**Issue by isomov** [webcamoid/akvirtualcamera#44]
Hello! Many thanks for the excellent library!

I have a question: is there a way to send frames from python to your virtual cam?

**Comment by hipersayanX** [comment]
[Here](https://github.com/webcamoid/akvirtualcamera/blob/master/share/examples/) you have some examples in C, you can adapt the examples to make them work with subprocess.Popen() in Python.

**Comment by isomov** [comment]
Thanks for the answer! Seems like a solution
