### ISSUE TITLE
Virtual Camera "Can't Start Stream" in Mac

### ISSUE THREAD

**Issue by halilkarab** [webcamoid/akvirtualcamera#51]
## Summary

Hi, I build the AkVirtualCamera from source. I followed the wiki step by step. I added device, started the service, added format to the camera. Now, my camera is detected by zoom.us. I can use set-picture command to set default png etc. However, there is a problem with the ipcbridge that doesnt let me stream using ffmpeg. 

## Current Behavior

I can't make stream using ffmpeg. I set log level 7 to gain more information. Here is a sample of my output even in the simplest command:
> ./AkVirtualCamManager devices
177 debug: bool AkVirtualCamera::IpcBridge::registerPeer(bool)
189 debug: Requesting service.
199 debug: Setting event handler.
208 debug: Requesting port.
285 debug: FAILED

and device information normally

## Expected Behavior
I expect program to work properly.

## Your Environment

* akvirtualcamera inormation: main branch
* Operating System information: MacOS Monterey 12.6

**Comment by hipersayanX** [comment]
Is AkVCamAssistant running?

**Comment by hipersayanX** [comment]
It's already [documented in the wiki](https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install#mac-2), the service need to be installed to pass data between the clients, otherwise the virtual camera will never work.

**Comment by halilkarab** [comment]
I had already installed the service. My point is following. Assume I build the files in a folder named akv/buıild placed in Desktop. Then if I try to make a operation in manager the output I have shared is shown, also I can't start stream using ffmpeg etc. However, If I copy the plugin and paste it under the Applications directory of Mac, no error message is shown and I can start a stream. In both cases my services are running.

**Comment by hipersayanX** [comment]
>If I copy the plugin and paste it under the Applications directory of Mac, no error message is shown and I can start a stream.

Because you had the ```/Library/CoreMediaIO/Plug-Ins/DAL/AkVirtualCamera.plugin``` folder still linked to your /Applications folder, again, read the documentation from start to the end, it's all in there.
