### ISSUE TITLE
Unable to find virtual camera on M1 Mac (Chrome, Firefox, Zoom)

### ISSUE THREAD

**Issue by mattrossman** [webcamoid/akvirtualcamera#52]
## Summary

After installing the latest AkVirtualCamera `.pkg` on my M1 Mac and following the [configuration guide](https://github.com/webcamoid/akvirtualcamera/wiki/Configure-the-cameras), I am unable to see the virtual camera in any client applications.

## Current Behavior

In the browser, I use https://webcamtests.com/ to enumerate available cameras. I only see my existing cameras here, I don't see the new virtual camera. I have tested this in the latest Chrome and Firefox. I don't see the new virtual camera in Zoom either.

## Expected Behavior

I should see some virtual camera listing appear here, at least with the default "no signal" dots pattern.

## Steps to Reproduce

1.  Download and install the [9.1.0 `.pkg`](https://github.com/webcamoid/akvirtualcamera/releases/tag/9.1.0)
3.  Open a terminal
4.  Configure a virtual camera as follows:

```bash
$ alias AkVCamManager=/Applications/AkVirtualCamera/AkVirtualCamera.plugin/Contents/Resources/AkVCamManager

$ AkVCamManager add-device "AkVirtualCamera"
Device created as AkVCamVideoDevice0

$ AkVCamManager add-format AkVCamVideoDevice0 YUY2 640 480 30

$ AkVCamManager update
```
5. Restart Chrome and navigate to https://webcamtests.com/ granting permission as needed
6. Inspect dropdown of detected devices

## Suggestions and tips

🤷‍♂️

## Your Environment

* akvirtualcamera inormation: 9.1.0 for Mac
* Operating System information: MacOS 12.6.1 Monterey, Apple M1 Pro
* Any other useful information: (below)

I have other virtual camera applications installed such as OBS Virtual Camera, I'm not sure if that would cause some conflict.

<details>
<summary>Output of <code>AkVCamManager dump</code></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<info>
    <devices>
        <device>
            <id>AkVCamVideoDevice0</id>
            <description>AkVirtualCamera</description>
            <formats>
                <format>
                    <pixel-format>YUY2</pixel-format>
                    <width>640</width>
                    <height>480</height>
                    <fps>30/1</fps>
                </format>
                <format>
                    <pixel-format>RGB32</pixel-format>
                    <width>640</width>
                    <height>480</height>
                    <fps>30/1</fps>
                </format>
                <format>
                    <pixel-format>RGB24</pixel-format>
                    <width>640</width>
                    <height>480</height>
                    <fps>30/1</fps>
                </format>
            </formats>
            <controls>
                <control>
                    <id>hflip</id>
                    <description>Horizontal Mirror</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
                <control>
                    <id>vflip</id>
                    <description>Vertical Mirror</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
                <control>
                    <id>scaling</id>
                    <description>Scaling</description>
                    <type>Menu</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                    <menu>
                        <item>Fast</item>
                        <item>Linear</item>
                    </menu>
                </control>
                <control>
                    <id>aspect_ratio</id>
                    <description>Aspect Ratio</description>
                    <type>Menu</type>
                    <minimum>0</minimum>
                    <maximum>2</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                    <menu>
                        <item>Ignore</item>
                        <item>Keep</item>
                        <item>Expanding</item>
                    </menu>
                </control>
                <control>
                    <id>swap_rgb</id>
                    <description>Swap RGB</description>
                    <type>Boolean</type>
                    <minimum>0</minimum>
                    <maximum>1</maximum>
                    <step>1</step>
                    <default-value>0</default-value>
                    <value>0</value>
                </control>
            </controls>
        </device>
    </devices>
    <input-formats>
        <pixel-format>RGB24</pixel-format>
    </input-formats>
    <default-input-format>RGB24</default-input-format>
    <output-formats>
        <pixel-format>RGB32</pixel-format>
        <pixel-format>RGB24</pixel-format>
        <pixel-format>UYVY</pixel-format>
        <pixel-format>YUY2</pixel-format>
    </output-formats>
    <default-output-format>YUY2</default-output-format>
    <clients>
    </clients>
    <picture></picture>
    <loglevel>-1</loglevel>
</info>
```

</details>

## Other things I have tried

* I tried [building and installing from source](https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install), with the same result
* I verified that `sudo launchctl list` includes an entry for `org.webcamoid.cmio.AkVCam.Assistant`
* I tried adding another format set to `RGB24` per the suggestion in #36
* I tried changing the fallback picture with `AkVCamManager set-picture`
* I tried restarting the browser and Zoom applications
* I checked the output of `AkVCamManager clients` while enumerating media devices in the browser, I don't see anything in the output

**Comment by hipersayanX** [comment]
The pkg is for x86_64 not for ARM M1, it won't work there.

>I tried [building and installing from source](https://github.com/webcamoid/akvirtualcamera/wiki/Build-and-install), with the same result

Run ```/Applications/AkVirtualCamera/uninstall.sh``` for uninstalling everything you have installed from the pkg.
When you compiled from the source, you probably did not linked the plugin or the plist file was not properly set.

**Comment by mattrossman** [comment]
Interestingly, I tried building from source before I tried the pkg installation, so I'm pretty sure it wasn't a conflict from the pkg install.

However, I just ran the uninstall script and re-tried the source build. It works! I don't know what I did differently this time 🙃 but I won't question it. I wish there was some error message that could explain what wasn't working before.

**Comment by hipersayanX** [comment]
I'll try later to add a M1 build and mark the architecture of the installer, but just in case, I don't have a M1 Mac to test it, so I can't go much further than that.
