### ISSUE TITLE
Apparently constantly crashes in the background...

### ISSUE THREAD

**Issue by ayunami2000** [webcamoid/akvirtualcamera#7]
When webcamoid is not running, apparently AkVCamAssistant.exe is, and is crashing multiple times a day.
![image](https://user-images.githubusercontent.com/24785136/99698237-8b762400-2a5e-11eb-8c77-6b4cf7e214b9.png)

Clicking a random one gives this:
![image](https://user-images.githubusercontent.com/24785136/99698517-e1e36280-2a5e-11eb-8bab-421bfb228681.png)

After some point, they all changed slightly, which I suspect is a change in windows but I'm not quite sure (after a search it seems the bucket id is Microsoft's way of tracking the errors from this specific program):
![image](https://user-images.githubusercontent.com/24785136/99698671-0ccdb680-2a5f-11eb-8db7-60b714a1d08a.png)

**Comment by hipersayanX** [comment]
The problem is that I can't reproduce the issue, that log does not show nothing useful, try with ```AkVCamManager set-loglevel 7```.

**Comment by ayunami2000** [comment]
1) How do I set those parameters? The program runs automatically by some startup script or something and restarts itself after it crashes.
2) I found ONE listing on google showing that the issue exists elsewhere. Note that this is not my computer and isn't focused around this specific issue [but](https://answers.ea.com/ea/attachments/ea/star-wars-squadrons-bug-reports-en/298/1/DxDiag.txt).... _(on web archive if link decides to die)_
3) I will run that command manually & I'll stop the other process. Later I will check for error logs. Where would it log to?
4) Webcamoid itself has always been really buggy for me and often quits, forcing me to reset the config. I forgot how I did that but...it's a regular issue whenever I (rarely) use webcamoid. Probably should be a separate issue

**Comment by ayunami2000** [comment]
Also: One similarity I found between my device and the other device is that we both use NVIDIA and both have multiple graphics cards (although I only have one NVIDIA and one Intel)

**Comment by ayunami2000** [comment]
It hasn't made any log files (despite being reported as crashed 3 hours ago), and I can't find `AkVCamManager`. Also, looking at my webcamoid folder I found that, strangely, there is a copy of the AkVirtualCamera.plugin folder (with the same files!). So one `AkVirtualCamera.plugin` folder is in `C:\Program Files\`, and another in `D:\webcamoid\share\`. Is it possible that changing the install location breaks some parts of the program?

**Comment by ayunami2000** [comment]
I just tried to reinstall it using the maintenance tool exe, but it still crashes upon running right after install

**Comment by hipersayanX** [comment]
While writing this answer I figured out that I forgot to ask you, you installed the virtual camera from Webcamoid 8.7.1, right? if that's the case you don't have AkVCamManager and all the debugging facilities of the new plugin. Uninstall the old plugin like this:

* Remove all virtual cameras from Webcamoid from the Outputs menu.
* Uninstall Webcamoid.
* Execute [this script](https://gist.github.com/hipersayanX/1de72ae55d0d1e746ef133391565bc05) as administrator to uninstall the plugin.
* And finally install [Webcamoid](https://bintray.com/webcamoid/webcamoid/webcamoid/daily) and [AkVirtualCamera](https://bintray.com/webcamoid/webcamoid/akvirtualcamera/daily) from the daily build.

_AkVCamManager_ is located at _C:\Program Files\AkVirtualCamera.plugin\x64\AkVCamManager.exe_ or _C:\Program Files\AkVirtualCamera.plugin\x86\AkVCamManager.exe_, you can open a CMD and then call AkVCamManager as:

```
set Path=C:\Program Files\AkVirtualCamera.plugin\x64;%Path%
AkVCamManager set-loglevel 7
```

>I just tried to reinstall all of webcamoid using the maintenance tool exe, but it still crashes upon running right after install. Should this be moved to another issue elsewhere? I ask because these could be related

Probably yes.

>Edit: Ok im like 9999999% sure that webcamoid crashes because I have a webcam device that is not in use (OBS virtual camera). It's still an issue because that makes the entire application crash just because of that one device. This could potentially be causing issues with AkVCam as well
>Edit 2: I was right, and OBS comes with a virtual camera now so i no longer need this problematic plugin that causes issues with multiple applications that use the camera.

Open a bug for this, I'll try to find a way to avoid the crash with that plugin.

**Comment by ayunami2000** [comment]
I don't have AkVcamManager; I have AkVcamAssistant. And yes, it's in that
directory, and it's the only exe in that x64 folder. (Same for x32 folder)
and only the placeholder image is in the share folder (which I replaced
with a custom image with the same name (which works))

**Comment by hipersayanX** [comment]
>I don't have AkVcamManager; I have AkVcamAssistant. And yes, it's in that
directory, and it's the only exe in that x64 folder. (Same for x32 folder)
and only the placeholder image is in the share folder (which I replaced
with a custom image with the same name (which works))

You have the old plugin, do as I said before and uninstall it.

**Comment by ayunami2000** [comment]
Ok I did that, it is no longer crashing but now there is no virtual camera...the "add output" option does not appear to add any outputs, yet Virtual Camera is listed in the plugins section...

**Comment by ayunami2000** [comment]
Closing because original issue has been fixed.
