### ISSUE TITLE
I want to use other programs to write data to the shared memory of the virtual camera. How do I do that?

### ISSUE THREAD

**Issue by qq978358810** [webcamoid/akvirtualcamera#72]
How do I do that?

**Comment by hipersayanX** [comment]
Its all explained in  the [wiki](https://github.com/webcamoid/akvirtualcamera/wiki).

**Comment by qq978358810** [comment]
> Its all explained in  the [wiki](https://github.com/webcamoid/akvirtualcamera/wiki).

Thanks.
