### ISSUE TITLE
AkVcamManager secretly requires administrator prompt to update

### ISSUE THREAD

**Issue by ayunami2000** [webcamoid/akvirtualcamera#8]
## Summary
running `AkVcamManager.exe update` in non-elevated command prompt fails because of access issues
## Current Behavior

**normal cmd:** `AkVcamManager.exe update`
![image](https://user-images.githubusercontent.com/24785136/99911482-ba8ccf80-2cc2-11eb-958f-468288cdc7c1.png)
log file:
![image](https://user-images.githubusercontent.com/24785136/99911255-1b1b0d00-2cc1-11eb-81e2-e3855f22f24c.png)

**admin cmd:** `AkVcamManager.exe update`
![image](https://user-images.githubusercontent.com/24785136/99911464-94672f80-2cc2-11eb-8b0f-b1dee65916e0.png)
log file:
![image](https://user-images.githubusercontent.com/24785136/99911512-ea3bd780-2cc2-11eb-9e54-7db8ce9fbf4c.png)

## Expected Behavior

At LEAST tell me that it must be run as administrator (btw this is loglevel 7), but preferably make it auto run itself as administrator thus showing the admin prompt

## Steps to Reproduce

If akvirtualcamera crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue bellow:

1.  normal cmd prompt
2.  add device using `AkVcamManager.exe` in cmd
3.  `AkVcamManager.exe update`
4.  check log file it references
5.  oh, it errored! who knew
6.  try with administrator cmd prompt (note: device is still there from before so that must have succeeded i guess)
7.  `AkVcamManager.exe update`
8.  check log file it references
9.  no error

## Suggestions and tips
force the program to show administrator prompt when necessary

## Your Environment
* AkVirtualCamera daily build: (build-info.txt below)
```
Commit hash: f2ca25c5c8f10df04dbbecefd73fce0e08c18f68
Build log URL: https://travis-ci.org/webcamoid/akvirtualcamera/builds/744660170

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

Wine Version: wine-5.21
Windows Version: Microsoft Windows 6.1.7601
```
* Operating System information: Windows 10 Home 64-bit OS build 19041.630
* Any other useful information: already listed above

**Comment by hipersayanX** [comment]
>At LEAST tell me that it must be run as administrator

I did not documented it yet because is not finished, I'm still working on it :laughing: 

>(btw this is loglevel 7), but preferably make it auto run itself as administrator thus showing the admin prompt

The manager is supposed to be a full CLI command, if you want to run the command as an administrator you must use the [runas](https://www.windows-commandline.com/windows-runas-command-prompt/) command, the same way you use ```sudo``` in GNU/Linux, or Mac.

>force the program to show administrator prompt when necessary

Nope, this must be done from the client GUI, in CLI you must use runas.

**Comment by hipersayanX** [comment]
>>force the program to show administrator prompt when necessary

>Nope, this must be done from the client GUI, in CLI you must use runas.

Well, at the end I did :man_shrugging:, I thought runas will trigger the UAC dialog and it did not. Now its possible to run the manager in a normal console, and it will ask for administrator permissions when required.

**Comment by hipersayanX** [comment]
Closing because solved.
